# Generated by Django 4.0.4 on 2022-05-31 19:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(upload_to=core.models.get_media_file_path, verbose_name='Media'),
        ),
    ]
