# Generated by Django 4.0.4 on 2022-06-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
